### ISSUE TITLE
Take the words "-for-Student" off  from the title  

### ISSUE THREAD

**Issue by DaveSimoes** [DaveSimoes/React_Helpful_Tutorial-BR#1]
Take the word "-for-Student" off  from the title

**Comment by Brijeshthummar02** [comment]
@DaveSimoes do you want to remove it from repo name or readme file?

**Comment by DaveSimoes** [comment]
Hi @Brijeshthummar02 .
Yes !! Please take from repo name AND readme file ...
Let just "2024", please.
